stages:
  - build

build:
  image: node:latest
  stage: build
  script:
    - cd bobby
    - npm install
    - npm run build
    - npm run lint
    - mv public bobby
    - apt update -y && apt install -y zip
    - zip bobby.zip -r bobby
  artifacts:
    paths:
      - bobby/bobby.zip
