stages:
  - build
  - release

build:
  image: node:latest
  stage: build
  script:
    - npm clean-install
    - npm run build
    - npm run coverage
    - npm run lint
    - mv public bobby
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    paths:
      - bobby

release_job:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Creating release $CI_COMMIT_TAG"
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
    tag_name: $CI_COMMIT_TAG
    assets:
      links:
        - name: 'Bobby'
          url: '$CI_REPOSITORY_URL/-/jobs/artifacts/$CI_COMMIT_TAG/download?job=build'
          link_type: package
